YFLAGS = -d

cfg1:	cfg1.o lex1.o
		gcc cfg1.o lex1.o -o cfg1 -ll

bal:	bal.o bal.lex.o
		gcc bal.o bal.lex.o -o bal -ll

palindrome:	palindrome.o palindrome.lex.o
		gcc palindrome.o palindrome.lex.o -o palindrome -ll
